alias l='ls -GF'
alias ls='ls -GF'
alias ll='ls -laGF'
alias pd='pwd'
alias ..='cd ..'
alias chrome='open -a "Google Chrome'
alias dev='cd ~/Developer'
alias corsChrome='open -n -a /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --args --user-data-dir="/tmp/chrome_dev_test" --disable-web-security'
alias reload='source ~/.zshrc'
