# alias l='ls -GF'
# alias ls='ls -GF'
# alias ll='ls -laGF'
alias l='ls'
alias ls="exa --icons --group-directories-first"
alias ll="exa --icons --group-directories-first -l -a"
alias pd='pwd'
alias ..='cd ..'
alias chrome='open -a "Google Chrome'
alias dev='cd ~/Developer'
alias home='cd ~/'
alias reload='source ~/.zshrc'
alias cls='clear'
